# Generated by Django 4.2.15 on 2024-08-29 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_watchlist'),
        ('jwt_auth', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(related_name='watched_by_users', to='products.product'),
        ),
    ]
