# Generated by Django 4.2.15 on 2024-08-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_image_url_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='image_url',
        ),
        migrations.AddField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
